DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'polyleads') THEN
        CREATE SCHEMA polyleads;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS polyleads."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "DocumentGroups" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ParentGroupId" bigint,
    "Name" character varying(128) NOT NULL,
    "Description" character varying(512) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" uuid,
    CONSTRAINT "PK_DocumentGroups" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DocumentGroups_DocumentGroups_ParentGroupId" FOREIGN KEY ("ParentGroupId") REFERENCES "DocumentGroups" ("Id")
);

CREATE TABLE "StorageObjects" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "StorageAlias" character varying(64) NOT NULL,
    "StorageId" character varying(64) NOT NULL,
    CONSTRAINT "PK_StorageObjects" PRIMARY KEY ("Id")
);

CREATE TABLE "FileEntries" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(128) NOT NULL,
    "Extension" character varying(8) NOT NULL,
    "Size" bigint NOT NULL,
    "StorageObjectId" bigint NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" uuid,
    CONSTRAINT "PK_FileEntries" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FileEntries_StorageObjects_StorageObjectId" FOREIGN KEY ("StorageObjectId") REFERENCES "StorageObjects" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Documents" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "FileEntryId" bigint,
    "Name" character varying(128) NOT NULL,
    "Description" character varying(512) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" uuid,
    CONSTRAINT "PK_Documents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Documents_FileEntries_FileEntryId" FOREIGN KEY ("FileEntryId") REFERENCES "FileEntries" ("Id")
);

CREATE TABLE "FileRecognitionStatuses" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "FileEntryId" bigint NOT NULL,
    "AssignedAt" timestamp with time zone NOT NULL,
    "Value" integer NOT NULL,
    CONSTRAINT "PK_FileRecognitionStatuses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FileRecognitionStatuses_FileEntries_FileEntryId" FOREIGN KEY ("FileEntryId") REFERENCES "FileEntries" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RecognitionResults" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "FileEntryId" bigint NOT NULL,
    "AllText" character varying(65536) NOT NULL,
    "RecognizedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RecognitionResults" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RecognitionResults_FileEntries_FileEntryId" FOREIGN KEY ("FileEntryId") REFERENCES "FileEntries" ("Id") ON DELETE CASCADE
);

CREATE TABLE "DocumentInGroups" (
    "DocumentId" bigint NOT NULL,
    "DocumentGroupId" bigint NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" uuid,
    CONSTRAINT "PK_DocumentInGroups" PRIMARY KEY ("DocumentId", "DocumentGroupId"),
    CONSTRAINT "FK_DocumentInGroups_DocumentGroups_DocumentGroupId" FOREIGN KEY ("DocumentGroupId") REFERENCES "DocumentGroups" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DocumentInGroups_Documents_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES "Documents" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_DocumentGroups_ParentGroupId" ON "DocumentGroups" ("ParentGroupId");

CREATE INDEX "IX_DocumentInGroups_DocumentGroupId" ON "DocumentInGroups" ("DocumentGroupId");

CREATE UNIQUE INDEX "IX_Documents_FileEntryId" ON "Documents" ("FileEntryId");

CREATE UNIQUE INDEX "IX_FileEntries_StorageObjectId" ON "FileEntries" ("StorageObjectId");

CREATE INDEX "IX_FileRecognitionStatuses_FileEntryId" ON "FileRecognitionStatuses" ("FileEntryId");

CREATE INDEX "IX_RecognitionResults_FileEntryId" ON "RecognitionResults" ("FileEntryId");

INSERT INTO polyleads."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240323224728_Initial', '8.0.3');

COMMIT;

START TRANSACTION;

CREATE TABLE "RoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id")
);

CREATE TABLE "Roles" (
    "Id" uuid NOT NULL,
    "Name" text,
    "NormalizedName" text,
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "UserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id")
);

CREATE TABLE "UserLogins" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    CONSTRAINT "PK_UserLogins" PRIMARY KEY ("UserId")
);

CREATE TABLE "UserRoles" (
    "RoleId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("RoleId")
);

CREATE TABLE "Users" (
    "Id" uuid NOT NULL,
    "UserName" text,
    "NormalizedUserName" text,
    "Email" text,
    "NormalizedEmail" text,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "UserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId")
);

INSERT INTO polyleads."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240324220841_AddedIdentityStore', '8.0.3');

COMMIT;

START TRANSACTION;

ALTER TABLE "UserTokens" DROP CONSTRAINT "PK_UserTokens";

ALTER TABLE "Users" DROP CONSTRAINT "PK_Users";

ALTER TABLE "UserRoles" DROP CONSTRAINT "PK_UserRoles";

ALTER TABLE "UserLogins" DROP CONSTRAINT "PK_UserLogins";

ALTER TABLE "UserClaims" DROP CONSTRAINT "PK_UserClaims";

ALTER TABLE "Roles" DROP CONSTRAINT "PK_Roles";

ALTER TABLE "RoleClaims" DROP CONSTRAINT "PK_RoleClaims";

ALTER TABLE "UserTokens" RENAME TO "AspNetUserTokens";

ALTER TABLE "Users" RENAME TO "AspNetUsers";

ALTER TABLE "UserRoles" RENAME TO "AspNetUserRoles";

ALTER TABLE "UserLogins" RENAME TO "AspNetUserLogins";

ALTER TABLE "UserClaims" RENAME TO "AspNetUserClaims";

ALTER TABLE "Roles" RENAME TO "AspNetRoles";

ALTER TABLE "RoleClaims" RENAME TO "AspNetRoleClaims";

ALTER TABLE "AspNetUsers" ALTER COLUMN "UserName" TYPE character varying(256);

ALTER TABLE "AspNetUsers" ALTER COLUMN "NormalizedUserName" TYPE character varying(256);

ALTER TABLE "AspNetUsers" ALTER COLUMN "NormalizedEmail" TYPE character varying(256);

ALTER TABLE "AspNetUsers" ALTER COLUMN "Email" TYPE character varying(256);

ALTER TABLE "AspNetUsers" ADD "FirstName" text NOT NULL DEFAULT '';

ALTER TABLE "AspNetUsers" ADD "LastName" text NOT NULL DEFAULT '';

ALTER TABLE "AspNetUsers" ADD "Patronymic" text;

ALTER TABLE "AspNetRoles" ALTER COLUMN "NormalizedName" TYPE character varying(256);

ALTER TABLE "AspNetRoles" ALTER COLUMN "Name" TYPE character varying(256);

ALTER TABLE "AspNetRoles" ADD "FirstName" text NOT NULL DEFAULT '';

ALTER TABLE "AspNetRoles" ADD "LastName" text NOT NULL DEFAULT '';

ALTER TABLE "AspNetRoles" ADD "Patronymic" text;

ALTER TABLE "AspNetUserTokens" ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");

ALTER TABLE "AspNetUsers" ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");

ALTER TABLE "AspNetUserRoles" ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");

ALTER TABLE "AspNetUserLogins" ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");

ALTER TABLE "AspNetUserClaims" ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");

ALTER TABLE "AspNetRoles" ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");

ALTER TABLE "AspNetRoleClaims" ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

ALTER TABLE "AspNetRoleClaims" ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE;

ALTER TABLE "AspNetUserClaims" ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE "AspNetUserLogins" ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE "AspNetUserRoles" ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE;

ALTER TABLE "AspNetUserRoles" ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE "AspNetUserTokens" ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

INSERT INTO polyleads."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240326171506_AddedFeaturesApplicationUser', '8.0.3');

COMMIT;

START TRANSACTION;

ALTER TABLE "AspNetRoles" DROP COLUMN "FirstName";

ALTER TABLE "AspNetRoles" DROP COLUMN "LastName";

ALTER TABLE "AspNetRoles" DROP COLUMN "Patronymic";

ALTER TABLE "AspNetUsers" ALTER COLUMN "Patronymic" TYPE character varying(32);

ALTER TABLE "AspNetUsers" ALTER COLUMN "LastName" TYPE character varying(32);

ALTER TABLE "AspNetUsers" ALTER COLUMN "FirstName" TYPE character varying(32);

INSERT INTO polyleads."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240326192720_RemovedPropertiesFromApplicationRole', '8.0.3');

COMMIT;

START TRANSACTION;

ALTER TABLE "Documents" DROP CONSTRAINT "FK_Documents_FileEntries_FileEntryId";

ALTER TABLE "FileRecognitionStatuses" DROP CONSTRAINT "FK_FileRecognitionStatuses_FileEntries_FileEntryId";

ALTER TABLE "RecognitionResults" DROP CONSTRAINT "FK_RecognitionResults_FileEntries_FileEntryId";

DROP TABLE "DocumentInGroups";

DROP TABLE "FileEntries";

DROP TABLE "DocumentGroups";

DROP TABLE "StorageObjects";

DROP INDEX "IX_RecognitionResults_FileEntryId";

DROP INDEX "IX_FileRecognitionStatuses_FileEntryId";

DROP INDEX "IX_Documents_FileEntryId";

ALTER TABLE "RecognitionResults" DROP COLUMN "FileEntryId";

ALTER TABLE "FileRecognitionStatuses" DROP COLUMN "FileEntryId";

ALTER TABLE "Documents" DROP COLUMN "FileEntryId";

INSERT INTO polyleads."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240420134117_RemovedUnusedEntities', '8.0.3');

COMMIT;

START TRANSACTION;

ALTER TABLE "Documents" ADD "Link" text NOT NULL DEFAULT '';

INSERT INTO polyleads."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240420142549_Added Url to Document', '8.0.3');

COMMIT;

START TRANSACTION;

ALTER TABLE "AspNetUserTokens" DROP CONSTRAINT "PK_AspNetUserTokens";

ALTER TABLE "AspNetUserRoles" DROP CONSTRAINT "PK_AspNetUserRoles";

DROP INDEX "IX_AspNetUserRoles_RoleId";

ALTER TABLE "AspNetUserLogins" DROP CONSTRAINT "PK_AspNetUserLogins";

DROP INDEX "IX_AspNetUserLogins_UserId";

ALTER TABLE "Documents" RENAME COLUMN "UpdatedBy" TO "UpdatedById";

ALTER TABLE "Documents" RENAME COLUMN "DeletedBy" TO "DeletedById";

ALTER TABLE "Documents" RENAME COLUMN "CreatedBy" TO "CreatedById";

ALTER TABLE "AspNetUserTokens" ALTER COLUMN "Name" DROP NOT NULL;

ALTER TABLE "AspNetUserTokens" ALTER COLUMN "LoginProvider" DROP NOT NULL;

ALTER TABLE "AspNetUserLogins" ALTER COLUMN "ProviderKey" DROP NOT NULL;

ALTER TABLE "AspNetUserLogins" ALTER COLUMN "LoginProvider" DROP NOT NULL;

ALTER TABLE "AspNetUserTokens" ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId");

ALTER TABLE "AspNetUserRoles" ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("RoleId");

ALTER TABLE "AspNetUserLogins" ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("UserId");

CREATE INDEX "IX_Documents_CreatedById" ON "Documents" ("CreatedById");

CREATE INDEX "IX_Documents_DeletedById" ON "Documents" ("DeletedById");

CREATE INDEX "IX_Documents_UpdatedById" ON "Documents" ("UpdatedById");

CREATE INDEX "IX_AspNetUserRoles_UserId" ON "AspNetUserRoles" ("UserId");

ALTER TABLE "Documents" ADD CONSTRAINT "FK_Documents_AspNetUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE "Documents" ADD CONSTRAINT "FK_Documents_AspNetUsers_DeletedById" FOREIGN KEY ("DeletedById") REFERENCES "AspNetUsers" ("Id");

ALTER TABLE "Documents" ADD CONSTRAINT "FK_Documents_AspNetUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

INSERT INTO polyleads."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240511163612_Added_foreign_keys', '8.0.3');

COMMIT;

START TRANSACTION;

ALTER TABLE "Documents" DROP CONSTRAINT "FK_Documents_AspNetUsers_UpdatedById";

ALTER TABLE "AspNetUserTokens" DROP CONSTRAINT "PK_AspNetUserTokens";

ALTER TABLE "AspNetUserRoles" DROP CONSTRAINT "PK_AspNetUserRoles";

DROP INDEX "IX_AspNetUserRoles_UserId";

ALTER TABLE "AspNetUserLogins" DROP CONSTRAINT "PK_AspNetUserLogins";

ALTER TABLE "Documents" RENAME COLUMN "Link" TO "DownloadUrl";

ALTER TABLE "Documents" ALTER COLUMN "UpdatedById" DROP NOT NULL;

ALTER TABLE "Documents" ALTER COLUMN "UpdatedAt" DROP NOT NULL;

UPDATE "AspNetUserTokens" SET "Name" = '' WHERE "Name" IS NULL;
ALTER TABLE "AspNetUserTokens" ALTER COLUMN "Name" SET NOT NULL;
ALTER TABLE "AspNetUserTokens" ALTER COLUMN "Name" SET DEFAULT '';

UPDATE "AspNetUserTokens" SET "LoginProvider" = '' WHERE "LoginProvider" IS NULL;
ALTER TABLE "AspNetUserTokens" ALTER COLUMN "LoginProvider" SET NOT NULL;
ALTER TABLE "AspNetUserTokens" ALTER COLUMN "LoginProvider" SET DEFAULT '';

UPDATE "AspNetUserLogins" SET "ProviderKey" = '' WHERE "ProviderKey" IS NULL;
ALTER TABLE "AspNetUserLogins" ALTER COLUMN "ProviderKey" SET NOT NULL;
ALTER TABLE "AspNetUserLogins" ALTER COLUMN "ProviderKey" SET DEFAULT '';

UPDATE "AspNetUserLogins" SET "LoginProvider" = '' WHERE "LoginProvider" IS NULL;
ALTER TABLE "AspNetUserLogins" ALTER COLUMN "LoginProvider" SET NOT NULL;
ALTER TABLE "AspNetUserLogins" ALTER COLUMN "LoginProvider" SET DEFAULT '';

ALTER TABLE "AspNetUserTokens" ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");

ALTER TABLE "AspNetUserRoles" ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");

ALTER TABLE "AspNetUserLogins" ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

ALTER TABLE "Documents" ADD CONSTRAINT "FK_Documents_AspNetUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "AspNetUsers" ("Id");

INSERT INTO polyleads."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240514183641_FixedDocumentEntity', '8.0.3');

COMMIT;

START TRANSACTION;

CREATE TABLE "PermittedSource" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "BaseUrl" text NOT NULL,
    "Description" character varying(256) NOT NULL,
    CONSTRAINT "PK_PermittedSource" PRIMARY KEY ("Id")
);

INSERT INTO polyleads."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240516154932_Created_Permitted_Source', '8.0.3');

COMMIT;

